[colors]
foreground = "#292a24"
background = "#fbf9f4"
cursor_bg = "#292a24"
cursor_fg = "#fbf9f4"
selection_bg = "#dedbd3"
selection_fg = "#292a24"

ansi = [
  "#292a24",
  "#aa4e55",
  "#4f714b",
  "#835f10",
  "#536f88",
  "#7c619a",
  "#2d6c6c",
  "#b5b2ab",
]

brights = [
  "#6d675f",
  "#a44e31",
  "#3a5e37",
  "#87601b",
  "#486a88",
  "#6f578c",
  "#286363",
  "#fbf9f4",
]
