[colors]
foreground = "#DCE1E6"
background = "#272C33"
cursor_bg = "#DCE1E6"
cursor_fg = "#272C33"
selection_bg = "#3A414A"
selection_fg = "#DCE1E6"

ansi = [
  "#1C2127",
  "#D47A7F",
  "#56BCAE",
  "#C6A15A",
  "#56BCAE",
  "#B184D5",
  "#56BCAE",
  "#C2C9D0",
]

brights = [
  "#626C77",
  "#56BCAE",
  "#72D1C3",
  "#B184D5",
  "#72D1C3",
  "#C69AE7",
  "#72D1C3",
  "#DCE1E6",
]
