-- Gonna try rolling without this for a few days to see if I can scrap it

-- vim.pack.add { 'https://github.com/Saghen/blink.pairs' }
--
-- require 'blink.pairs' {
--   mappings = {
--     enabled = true,
--     -- cmdline = true,
--   },
--   highlights = {
--     enabled = true,
--     -- cmdline = true,
--     matchparen = {
--       enabled = true,
--
--       -- known issue where typing won't update matchparen highlight, disabled by default
--       -- cmdline = false,
--       -- group = 'BlinkPairsMatchParen',
--     },
--   },
-- }
