vim.pack.add({ "https://github.com/folke/snacks.nvim" })

require("snacks").setup({
    debug = { enabled = true },
    indent = {},
    input = {},
    picker = {},
    notify = {},
    zen = {},
})

vim.keymap.set("n", "<leader><leader>", function()
    Snacks.picker.buffers()
end, { desc = "[S]earch Buffers" })
vim.keymap.set("n", "<leader>sg", function()
    Snacks.picker.grep()
end, { desc = "[S]earch [G]rep" })
vim.keymap.set("n", "<leader>sw", function()
    Snacks.picker.grep_word()
end, { desc = "[S]earch [W]ord" })
vim.keymap.set("n", "<leader>sh", function()
    Snacks.picker.help()
end, { desc = "[S]earch [H]elp pages" })
vim.keymap.set("n", "<leader>sf", function()
    Snacks.picker.files()
end, { desc = "[S]earch [F]iles" })
vim.keymap.set("n", "<leader>s.", function()
    Snacks.picker.recent()
end, { desc = "[S]earch Recent files" })
vim.keymap.set("n", "<leader>su", function()
    Snacks.picker.undo()
end, { desc = "[S]earch [U]ndo history" })
vim.keymap.set("n", "<leader>sd", function()
    Snacks.picker.diagnostics()
end, { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>sk", function()
    Snacks.picker.keymaps()
end, { desc = "[S]earch [K]eymaps" })

vim.keymap.set("n", "gd", function()
    Snacks.picker.lsp_definitions()
end, { desc = "[G]oto [D]efinition" })
vim.keymap.set("n", "gD", function()
    Snacks.picker.lsp_declarations()
end, { desc = "[G]oto [D]eclaration" })
vim.keymap.set("n", "grr", function()
    Snacks.picker.lsp_references()
end, { desc = "[G]oto [R]eferences", nowait = true })
vim.keymap.set("n", "gI", function()
    Snacks.picker.lsp_implementations()
end, { desc = "[G]oto [I]mplementations" })
vim.keymap.set("n", "gy", function()
    Snacks.picker.lsp_type_definitions()
end, { desc = "[G]oto T[y]pe Definition" })

vim.keymap.set("n", "<leader>ss", function()
    Snacks.picker.lsp_symbols()
end, { desc = "[S]earch LSP [S]ymbols" })
vim.keymap.set("n", "<leader>sS", function()
    Snacks.picker.lsp_workspace_symbols()
end, { desc = "[S]earch LSP Workspace [S]ymbols" })
